<<<<<<< HEAD
#Spring Data Source
=======
# Spring Data Source ??
>>>>>>> 671eb93429d94c4e82b3477caea7b44133995424

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/examplesdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: cubric
    password: qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
<<<<<<< HEAD
 #database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
=======
 #   database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
>>>>>>> 671eb93429d94c4e82b3477caea7b44133995424
